CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_495CC1F9_9064_445E_8521_62985291C717 START WITH 6 BELONGS_TO_TABLE;     
CREATE CACHED TABLE PUBLIC.TAAGRUPADOR(
    FIID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_495CC1F9_9064_445E_8521_62985291C717) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_495CC1F9_9064_445E_8521_62985291C717,
    FCNOMBREAGRUPADOR VARCHAR(100) NOT NULL
);     
ALTER TABLE PUBLIC.TAAGRUPADOR ADD CONSTRAINT PUBLIC.PK_TAAGRUPADOR PRIMARY KEY(FIID);          
CREATE CACHED TABLE PUBLIC.TAELEMENTOTRADUCTOR(
    FIID BIGINT NOT NULL,
    FIIDTRADUCTOR BIGINT NOT NULL,
    FCCONSTANTE VARCHAR(39) NOT NULL,
    FITIPOAGRUPADOR TINYINT NOT NULL,
    FCVALOR VARCHAR(4000) DEFAULT ' ' NOT NULL
);     
ALTER TABLE PUBLIC.TAELEMENTOTRADUCTOR ADD CONSTRAINT PUBLIC.PK_TAELEMENTOTRADUCTOR PRIMARY KEY(FIID);         

CREATE CACHED TABLE PUBLIC.TATIPOFORMATEADOR(
    FIID TINYINT NOT NULL,
    FCDESCRIPCION VARCHAR(100) NOT NULL,
    FCFORMATO VARCHAR(100) NOT NULL,
    FIEJECUTARTRIM BOOLEAN DEFAULT FALSE NOT NULL
);    
ALTER TABLE PUBLIC.TATIPOFORMATEADOR ADD CONSTRAINT PUBLIC.PK_TATIPOFORMATEADOR PRIMARY KEY(FIID);             
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.TATIPOFORMATEADOR;        
INSERT INTO PUBLIC.TATIPOFORMATEADOR(FIID, FCDESCRIPCION, FCFORMATO, FIEJECUTARTRIM) VALUES
(1, 'VARCHAR2', '', FALSE),
(2, 'NUMBER', '', TRUE),
(3, 'DATE', 'dd-MM-YYYY', TRUE),
(4, 'TIMESTAMP', 'dd-MM-YYYY HH24:MI:SS', TRUE);             
ALTER TABLE PUBLIC.TAELEMENTOTRADUCTOR ADD CONSTRAINT PUBLIC.FK_TAELEMENTOTRADUCTOR_01 FOREIGN KEY(FIIDTRADUCTOR) REFERENCES PUBLIC.TAAGRUPADOR(FIID) NOCHECK; 
ALTER TABLE PUBLIC.TAELEMENTOTRADUCTOR ADD CONSTRAINT PUBLIC.FK_TAELEMENTOTRADUCTOR_02 FOREIGN KEY(FITIPOAGRUPADOR) REFERENCES PUBLIC.TATIPOFORMATEADOR(FIID) NOCHECK;         
